### ISSUE TITLE
OfType is not always redundant

### ISSUE THREAD

**Issue by jnyrup** [u2uconsult/codeanalyzers#1]
Removing `OfType<T>` when `T` is a reference type can have semantic changes, as it removes nulls. 

```c#
var strings = new string[] { "", null };
var stringsNonNull = strings.OfType<string>(); // triggers U2U1007
```

Related issue in another analyzer:
https://github.com/JosefPihrt/Roslynator/issues/172

**Comment by KrisVandermotten** [comment]
While it is true that `OfType<T>` removes nulls, if null removal is the goal, calling `OfType<T>` is hardly the best choice. Null removal is probably not the intent of the call.

Nevertheless, you have a point and we will consider improving the message.

**Comment by KrisVandermotten** [comment]
We have changed the wording as follows.

In

    IEnumerable<string> OfTypeString(IEnumerable<string> l) => l.OfType<string>();

we will report

    Do not call IEnumerable.OfType<string>() on an object of type IEnumerable<string>; use a different method to filter out null values
