### ISSUE TITLE
U2U1105 over exceptions

### ISSUE THREAD

**Issue by CheloXL** [u2uconsult/codeanalyzers#11]
Hi,
While I think that U2U1105 is of course beneficial for most cases, when I'm doing something like `throw new ArgumentException($"The argument ´{mimeTypeOrExtension}´ is not a valid mime type.", nameof(mimeTypeOrExtension));` I believe you can skip U2U1105 as the cost of the string interpolation is not really relevant at all, and it adds to the readability of the source code.

**Comment by KrisVandermotten** [comment]
Of course the performance is indeed not relevant in this case.

However, there are many kinds of such cases, and covering them all is impossible. You can of course suppress the warning or simply ignore it.

What is most readable may be in the eye of the beholder, but changing it to `throw new ArgumentException("The argument '" + mimeTypeOrExtension + "' is not a valid mime type.", nameof(mimeTypeOrExtension));` is an option too.

Of course, if and when [my pull request](https://github.com/dotnet/roslyn/pull/22595) to do this optimization in the compiler automatically is accepted, the whole question becomes moot (and the analyzer will be removed).

**Comment by CheloXL** [comment]
Sure. I used the above as an example, but usually my exceptions messages are quite descriptive and have several placeholders. And my suggestion was relevan only to Exceptions ctor, as I know that handling every single case would be a lot of work.

I hope your pull request gets merged, as I believe it is a quite interesting optimization.

**Comment by KrisVandermotten** [comment]
> And my suggestion was relevan only to Exceptions ctor

Sure, but even that can be debated. Would that apply to *all* exception types, or just to [boneheaded exceptions](https://blogs.msdn.microsoft.com/ericlippert/2008/09/10/vexing-exceptions/) such as `ArgumentException`? And if we do this for exceptions, what other cases might be next?

I feel this might be a can of worms, and at this stage, I think I'd rather not open it.

**Comment by wmjordan** [comment]
Currently my projects contains quite a few `U2U1105` warnings, most of which are almost in Exception constructors.
I hope that @KrisVandermotten 's pull request can get merged. So 1105 would not be an issue any more.

Maybe it is also possible to optimize the compiler to automatically provide an implicit workaround for `U2U1101` by automatically call `ToString` functions on concatenated values.

**Comment by KrisVandermotten** [comment]
The [pull request](https://github.com/dotnet/roslyn/pull/22595) has been merged. Starting with Visual Studio 2017 15.8 preview 3, the compiler will do this optimization automatically.

A new version of the performance analyzers will be made available soon, in which U2U1105 will no longer be a warning by default.
