### ISSUE TITLE
Help Viewer

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#12]
I am using VS2017 with the Help Viewer installed locally. Whenever I click on a link in the error list, such as `U2U****`, it launches the help viewer and says, "No results were found.". How do I make this follow the link to the web instead of trying to look locally?

**Comment by KrisVandermotten** [comment]
I'm afraid that's a question you'll have to ask Microsoft...

**Comment by josefpihrt** [comment]
https://github.com/dotnet/roslyn/issues/23602
