### ISSUE TITLE
What's U2U1018?

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#14]
There's not documentation about this code fix.

The following unsafe code triggers `U2U1018`: _Local variable 'a' can be type byte[]_.
I think it can be a false notification.

````C#
static unsafe bool Test(this byte[] source, byte[] target) {
	fixed (byte* a = source)
	fixed (byte* b = target) {
		var pa = (long*)a;
		var pb = (long*)b;
//		....
		return true;
	}
}
`````

**Comment by KrisVandermotten** [comment]
Thank you for reporting this bug. A fix has been published in version 2.11.1.

As for the documentation, work on that is in progress.
