### ISSUE TITLE
Code fix for U2U1010 could break unsafe classes

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#16]
If a class marked `unsafe` can be sealed, the code fix for U2U1010 will remove the `unsafe` when applying `sealed` to the declaration.

**Comment by KrisVandermotten** [comment]
Thanks for reporting this bug.

It is fixed in release 2.13.3, now available from the marketplace.

**Comment by wmjordan** [comment]
Thank you very much for the quick fix.
