### ISSUE TITLE
U2U1001 was not working in some classes

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#17]
U2U1001 was not showing up for this file:

https://github.com/wmjordan/mupdf/blob/master/MupdfSharp/Program.cs

The `Program` class could be marked static, so to the nested class `NativeMethods`.

**Comment by KrisVandermotten** [comment]
I'm sorry, but I cannot reproduce that. I cloned your repository, and the diagnostic is raised for both types.

    Message U2U1001 Class Program is stateless and can be declared static
        Program.cs line 9
    Message U2U1001 Class Program.NativeMethods is stateless and can be declared static
        Program.cs line 113

Make sure that the extension is enabled, and that a filter does not hide the message in the error list.

**Comment by wmjordan** [comment]
![screenshot](https://user-images.githubusercontent.com/12182730/34966716-ad2970e6-fa98-11e7-83a8-a2adfdcc618e.png)

I discovered that while the building configuration was `Debug`, everything was fine.
When I switch the build configuration from `Debug` to `Release`, the issue could be reproduced.
