### ISSUE TITLE
Settings options

### ISSUE THREAD

**Issue by jnothstine** [u2uconsult/codeanalyzers#19]
I like this tool and really appreciate it.  It would be nice if there was an option to set the issues to show up as warnings or errors.  I have an old project that has a ton of issues that this identifies.  I can't fix them all right now though.  When I compile my code, it shows a bunch of errors I need to ignore for now.

Thanks,

Jerry.

**Comment by KrisVandermotten** [comment]
You can [use the Visual Studio rule set editor](https://docs.microsoft.com/en-us/visualstudio/code-quality/working-in-the-code-analysis-rule-set-editor) to configure, per project, which issues are errors, warnings, or just reported for information.

Bear in mind however, that if you compile with ["Treat warnings as errors"](https://docs.microsoft.com/en-us/visualstudio/ide/reference/build-page-project-designer-csharp) set to "All", all warnings will be shown as errors.
