### ISSUE TITLE
Making a class static removes sealed from inner class

### ISSUE THREAD

**Issue by jnyrup** [u2uconsult/codeanalyzers#21]
Putting the cursor on `Program` and selecting "Make program static" removes the `sealed` modifier from the inner class `A`
```
class Program
{
    sealed class A
    {
        public int MyProperty { get; set; }
    }
}
```

![image](https://user-images.githubusercontent.com/919634/41719765-51e582e4-7561-11e8-9161-f6cf28e19dc4.png)

**Comment by KrisVandermotten** [comment]
Thanks for reporting. This is fixed in version 2.15.3.
