### ISSUE TITLE
Documentation for U2U1009

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#22]
Could you please write a documentation for U2U1009 demonstrating how to fix the problem?
I am sorry that I am new to `async` and `await`. I understood what that suggestion means but I did not know how to fix it efficiently.

**Comment by KrisVandermotten** [comment]
I added an example with an iterator. I'll add one with `async` and `await` soon, but it is similar of course.

**Comment by wmjordan** [comment]
The `async` and `await` pattern is a little bit nasty. They propagates to the root of the callers.

This article has discussed about that:
https://www.codeproject.com/Articles/1239585/The-Foreground-Await-Async-Anti-Pattern

**Comment by KrisVandermotten** [comment]
That article has nothing to with what U2U1009 reports. Also, it is inaccurate, if not incorrect.
