### ISSUE TITLE
Docs on U2U1212

### ISSUE THREAD

**Issue by CheloXL** [u2uconsult/codeanalyzers#23]
I'm not sure how to extract the subexpression of the lambda expression inside the expression without breaking the expression... (I'm not sure if I'm expressing it correctly) :expressionless:

**Comment by KrisVandermotten** [comment]
Could you give me an example of a lambda where a diagnostic is raised on a subexpression that cannot be extracted into a variable?

Note that version 2.18 fixes a bug causing false positives used to be reported.

**Comment by CheloXL** [comment]
Usually in every linq expression.. like FirstOrDefault(x => x.Id == id). I will check my projects with 2.18... Didn't know it was updated a few days ago.

**Comment by KrisVandermotten** [comment]
The diagnostic messages for U2U1212 have been improved in version 2.18.3, available now. I hope those help.

As for `FirstOrDefault(x => x.Id == id)`, no diagnostic should be reported for that code.
