### ISSUE TITLE
U2U1009 early state machine generation

### ISSUE THREAD

**Issue by bluntoze** [u2uconsult/codeanalyzers#36]
The warning can be hidden by wrapping the remaining code after the early exit in an else statement.
But that will still generate a state machine.

```C#
public async Task SomeMethodAsync(bool someCondition, CancellationToken cancellationToken = default)
{
            if (someCondition))
            {
                return;
            }
            else
            {
                var conditionFromGet= await GetConditionAsync(cancellationToken);

                if (!conditionFromGet)
                {
                    throw new UnauthorizedAccessException();
                }
            }
}
```

**Comment by KrisVandermotten** [comment]
Thank you for reporting this issue.

It was never the intention for this analyzer to catch all cases with early exits. Rather, the goal was to catch those cases that are easy to fix, i.e. where the fix does not render the code unreadable. The low-hanging fruit, so to speak.

That being said, we are looking into improving the analyzer, such that it can catch cases such as the one you present here.

At the same time, we are considering changing the default severity level from Warning to Info, for two reasons:
1. If we detect more cases, inevitably there will be more cases that users don't want to fix.
2. The issue has become less important, especially with `async` methods that return `ValueTask<T>`.

**Comment by KrisVandermotten** [comment]
Version 3.8.10 should fix this.
