### ISSUE TITLE
Question: U2U1107 of AppendLine

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#5]
The following code triggers U2U1107:
````C#
var sb = new StringBuilder();
....
sb.AppendLine(",");
....
````
However, there's no counterpart of `AppendLine(char)`, but `Append(char).AppendLine()` only.
No code fix is provided for this scenario at this moment.

Is it more appropriate to provide a code fix for that, which automatically changes the above statement to `sb.Append(',').AppendLine()`, or simply suppress the warning?

**Comment by KrisVandermotten** [comment]
We added a code fix in version 2.8 (now available).

**Comment by wmjordan** [comment]
Thank you for providing the fix.
Currently the fix was not so convenient to work with.
Given that the following code:
````C#
var sb = new StringBuilder(1000)
		.Append("Hello")
		.AppendLine(" ")
		.AppendLine("Word");
````
The `AppendLine` was indented.
After applying the fix, the leading tab-stops were removed.
````C#
var sb = new StringBuilder(1000)
		.Append("Hello")
.Append(' ').AppendLine()
		.AppendLine("Word");
````
Is it possible to preserve the indentations?

**Comment by KrisVandermotten** [comment]
Version 2.8.1 fixes that.
