### ISSUE TITLE
How to fix issue U2U1100 for OrdinalIgnoreCase comparison?

### ISSUE THREAD

**Issue by wmjordan** [u2uconsult/codeanalyzers#7]
The following code triggers warning U2U1100.
````C#
if (String.Compare(a, b, StringComparison.OrdinalIgnoreCase) == 0) {
   ....
}
````
The source code of `String.Compare` and `String.Equals` are almost the same, except that the former won't throw an exception when the first string is `null`, which is desirable in some cases that we don't know whether the first string is null or not.

Is there a more efficient way to do this type of `OrdinalIgnoreCase` comparison?

**Comment by KrisVandermotten** [comment]
Just use

    if (String.Equals(a, b, StringComparison.OrdinalIgnoreCase))
    {
    }

**Comment by wmjordan** [comment]
The above "optimization" will not bring positive result to the generated IL code out of the `Optimize` enabled C# compiler.

Given the following C# code:
````C#
private static void NewMethod(string a, string b) {
	if (String.Equals(a, b, StringComparison.OrdinalIgnoreCase)) {
		Console.WriteLine("a=b");
	}
	if (String.Compare(a, b, StringComparison.OrdinalIgnoreCase) == 0) {
		Console.WriteLine("a == b");
	}
}
````

When it is compiled with the Optimize option turned on in the compiler, the generated IL code was almost identical.
````asm
IL_0000: ldarg.0
IL_0001: ldarg.1
IL_0002: ldc.i4.5
IL_0003: call bool [mscorlib]System.String::Equals(string, string, valuetype [mscorlib]System.StringComparison)
IL_0008: brfalse.s IL_0014

IL_000a: ldstr "a=b"
IL_000f: call void [mscorlib]System.Console::WriteLine(string)

IL_0014: ldarg.0
IL_0015: ldarg.1
IL_0016: ldc.i4.5
IL_0017: call int32 [mscorlib]System.String::Compare(string, string, valuetype [mscorlib]System.StringComparison)
IL_001c: brtrue.s IL_0028

IL_001e: ldstr "a == b"
IL_0023: call void [mscorlib]System.Console::WriteLine(string)

IL_0028: ret
````
The internal IL code of the `String.Compare` and `String.Equals` are almost identical.
Thus there is little performance gain by replacing `String.Compare` with `String.Equals`.

I suggest that this warning should be removed in the upcoming release.

**Comment by wmjordan** [comment]
Further more, when I examined the IL code in `String.Equals`, I found that it is actually calling `System.Globalization.TextInfo::CompareOrdinalIgnoreCase(string, string)` like `String.Compare`, but with two more instructions.

````asm
IL_00e6: ldarg.0
IL_00e7: ldarg.1
IL_00e8: call int32 System.Globalization.TextInfo::CompareOrdinalIgnoreCase(string, string)
IL_00ed: ldc.i4.0 ; this op and the following op are additional instructions in String.Equals
IL_00ee: ceq ; which are not necessary in String.Compare
IL_00f0: ret
````

I think that `String.Equals` is theoretically slower than `String.Compare`.

**Comment by wmjordan** [comment]
Understood.
`String.Equals` compares `String.Length` first when it is doing ordinal comparison, which may be more efficient than `String.Compare` when two strings have unequal lengths.
